version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: steam_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - steam_network

#ajout d'elasticsearch

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
      container_name: steam_elastic
      environment:
        - discovery.type=single-node
        # On limite la RAM pour le PC 
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ports:
        - "9200:9200"
      volumes:
        - es_data:/usr/share/elasticsearch/data
      networks:
        - steam_network



  streamlit:
    build: .
    container_name: steam_app
    ports:
      - "8501:8501"
    depends_on:
      - mongodb
      - elasticsearch
    networks:
      - steam_network
    environment:
      - MONGO_HOST=mongodb
      - ES_HOST=elasticsearch
    volumes:
      - ./steam_project:/app/steam_project

networks:
  steam_network:
    driver: bridge

volumes:
  mongo_data:
  es_data: